/**
 * configCheck.ts
 *
 * A utility module that checks whether the application has been configured
 * with a valid config.json file before it tries to start or run.
 *
 * Why this file exists:
 *   When the NXF application is first deployed, it needs to go through the
 *   installation wizard before it can operate normally. The presence and
 *   validity of config.json is used as the signal that installation has been
 *   completed. This check allows other parts of the application (e.g. the
 *   root layout or middleware) to detect an unconfigured state and redirect
 *   the user to the installer automatically.
 *
 * What is config.json?
 *   A JSON file generated by the installer and saved to app/config.json.
 *   It contains the core runtime configuration for the application, most
 *   importantly the `dbType` field which tells the app which database adapter
 *   to use. Without this file the application has no idea how to connect to
 *   a database.
 *
 * ESM vs CommonJS — what is __dirname here?
 *   In older CommonJS Node.js modules, __dirname is a built-in variable that
 *   holds the directory path of the current file. In modern ESM (ES Modules),
 *   that variable does not exist automatically. The two lines:
 *     const __dirname = path.dirname(fileURLToPath(import.meta.url))
 *   recreate the same behaviour for ESM:
 *     import.meta.url  — the full file:// URL of the current module.
 *     fileURLToPath()  — converts that URL to a regular file system path.
 *     path.dirname()   — strips the filename to get just the directory.
 *
 * Exports:
 *   hasValidConfig() — returns true if config.json exists and contains a
 *                      valid dbType field, false otherwise.
 */

import fs               from 'fs'
import path             from 'path'
import { fileURLToPath } from 'url'

/**
 * hasValidConfig
 *
 * Checks whether a valid config.json file exists at the expected location
 * (app/config.json, one level above this file's directory).
 *
 * Validation criteria:
 *   1. The file must physically exist on disk.
 *   2. The file must contain valid JSON (no syntax errors).
 *   3. The parsed JSON must have a truthy `dbType` field, which indicates
 *      that the installer has completed the database configuration step.
 *
 * Why these specific checks?
 *   - Checking file existence first avoids a try/catch for the common case
 *     where the installer simply hasn't been run yet.
 *   - Wrapping JSON.parse in try/catch handles the edge case where the file
 *     was created but is empty or corrupted (e.g. an interrupted write).
 *   - Checking `config?.dbType` is the minimum signal that the installation
 *     wizard reached at least the database selection step. You can make this
 *     check stricter as your validation requirements grow.
 *
 * @returns {boolean} true  — config.json exists, is valid JSON, and has a
 *                            dbType field. The app is ready to run.
 *                   false — the file is missing, unreadable, invalid JSON,
 *                            or lacks a dbType. The app should redirect to
 *                            the installer.
 *
 * @example
 *   import { hasValidConfig } from '@/lib/configCheck'
 *
 *   if (!hasValidConfig()) {
 *     redirect('/install')
 *   }
 */
// export function hasValidConfig(): boolean {

//   // Reconstruct __dirname for ESM environments.
//   // In CommonJS this would simply be the built-in __dirname variable, but
//   // ESM modules do not have it, so we derive it from the module's own URL.
//   const __dirname  = path.dirname(fileURLToPath(import.meta.url))

//   // Build the absolute path to config.json.
//   // path.resolve() joins segments and normalises the result to an absolute
//   // path, regardless of where the process was started from.
//   // '../app/config.json' means: go one directory up from this file, then
//   // into the 'app' folder to find 'config.json'.
//   const configPath = path.resolve(__dirname, '../app/config.json')

//   // Short-circuit: if the file doesn't exist there is nothing to parse.
//   // Returning false here means the installer has not been run yet.
//   if (!fs.existsSync(configPath)) return false

//   try {
//     // Read the file synchronously as a UTF-8 string.
//     // This is acceptable here because hasValidConfig() is called during
//     // application startup/middleware, before any request handling begins.
//     const content = fs.readFileSync(configPath, 'utf-8')

//     // Parse the JSON string into a plain JavaScript object.
//     // If the file content is not valid JSON, JSON.parse throws a SyntaxError
//     // which is caught below, returning false.
//     const config = JSON.parse(content)

//     // Validate that the parsed config has a truthy dbType field.
//     // The !! operator converts the value to a strict boolean:
//     //   !!undefined → false
//     //   !!''        → false
//     //   !!'firebase'→ true
//      return !!config?.dbType

//   } catch {
//     // JSON.parse failed (syntax error or empty file) — treat as invalid.
//     return false
//   }

//   // config.ts
// }

// config.ts
export function hasValidConfig(): { selectedDb: string; installed: boolean } | null {
  const configPath = path.resolve(process.cwd(), 'underpeaks.config.json')

  if (!fs.existsSync(configPath)) return null

  try {
    const content = fs.readFileSync(configPath, 'utf-8')
    const config = JSON.parse(content)

    if (!config?.selectedDb) return null

    return config
  } catch {
    return null
  }
}