import { writeFile } from 'fs/promises';
import path from 'path';

const ENV_FILE_PATH = path.resolve(process.cwd(), '.env.local');
console.log('📝 ENV write path:', ENV_FILE_PATH);

// 🔒 ALWAYS SAFE WRAPPER
function envSafe(value: any): string {
  if (value === undefined || value === null) return '""';

  // keep numbers unquoted if you want (optional)
  if (typeof value === 'number') return String(value);

  const str = String(value);

  // escape quotes
  return `"${str.replace(/"/g, '\\"')}"`;
}

function extractMongoDbName(uri: string, fallback?: string) {
  try {
    const afterSlash = uri.split('.net/')[1] || '';
    const dbName = afterSlash.split('?')[0];
    return dbName || fallback || 'nxt_flutter';
  } catch {
    return fallback || 'nxt_flutter';
  }
}

function serializeServiceAccount(value: any) {
  let obj: any = typeof value === 'string' ? JSON.parse(value) : value;

  if (obj.private_key) {
    obj.private_key = obj.private_key.replace(/\r?\n/g, '\\n');
  }

  return JSON.stringify(obj);
}

function serializeFirebaseWebConfig(value: string | object) {
  let obj: any;

  if (typeof value === 'string') {
    value = value.trim().replace(/;$/, '');
    obj = eval('(' + value + ')'); // ⚠️ assume trusted input
  } else {
    obj = value;
  }

  return JSON.stringify(obj);
}

function ensureHttp(url: string) {
  if (!url) return url;
  if (!url.startsWith('http://') && !url.startsWith('https://')) {
    return `https://${url}`;
  }
  return url;
}

async function writeEnvFileFromObject(env: Record<string, any>) {
  console.log('📦 Received ENV payload:', env);

  if (!env.type) throw new Error('Missing "type" in env payload');

  const lines: string[] = [`# Generated by NXT_Flutter Installer`];

  // ✅ GLOBAL
  lines.push(`NEXT_DB_TYPE=${envSafe(env.type)}`);
  lines.push(`NEXT_PUBLIC_DB_TYPE=${envSafe(env.type)}`);
  lines.push(
    `NEXT_PUBLIC_APP_DOMAIN=${envSafe(
      ensureHttp(env.domain || 'localhost:3000')
    )}`
  );

  switch (env.type) {
    // ======================= MONGODB =======================
    case 'mongodb':
      if (!env.connectionString)
        throw new Error('MongoDB connectionString is required');

      lines.push(
        `NEXT_DB_MONGO_URI=${envSafe(env.connectionString)}`
      );

      lines.push(
        `NEXT_DB_MONGO_DB_NAME=${envSafe(
          extractMongoDbName(env.connectionString, env.databaseName)
        )}`
      );
      break;

    // ======================= MYSQL =======================
    case 'mysql':
      if (!env.host || !env.database || !env.user || !env.password)
        throw new Error(
          'MySQL config missing host, database, user, or password'
        );

      lines.push(`NEXT_DB_MYSQL_HOST=${envSafe(env.host)}`);
      lines.push(`NEXT_DB_MYSQL_PORT=${envSafe(env.port || 3306)}`);
      lines.push(`NEXT_DB_MYSQL_DATABASE=${envSafe(env.database)}`);
      lines.push(`NEXT_DB_MYSQL_USER=${envSafe(env.user)}`);
      lines.push(`NEXT_DB_MYSQL_PASSWORD=${envSafe(env.password)}`);
      break;

    // ======================= POSTGRES =======================
    case 'postgres':
      if (!env.host || !env.database || !env.user || !env.password)
        throw new Error(
          'Postgres config missing host, database, user, or password'
        );

      lines.push(`NEXT_DB_POSTGRES_HOST=${envSafe(env.host)}`);
      lines.push(`NEXT_DB_POSTGRES_PORT=${envSafe(env.port || 5432)}`);
      lines.push(`NEXT_DB_POSTGRES_DATABASE=${envSafe(env.database)}`);
      lines.push(`NEXT_DB_POSTGRES_USER=${envSafe(env.user)}`);
      lines.push(`NEXT_DB_POSTGRES_PASSWORD=${envSafe(env.password)}`);
      break;

    // ======================= SUPABASE =======================
    case 'supabase':
      const supabaseUrl = env.supabaseUrl || env.url;
      if (!supabaseUrl) throw new Error('Supabase URL missing');

      lines.push(
        `NEXT_PUBLIC_SUPABASE_URL=${envSafe(
          ensureHttp(supabaseUrl)
        )}`
      );

      if (env.anonKey) {
        lines.push(
          `NEXT_PUBLIC_SUPABASE_ANON_KEY=${envSafe(env.anonKey)}`
        );
      }

      if (env.serviceKey) {
        lines.push(
          `SUPABASE_SERVICE_ROLE_KEY=${envSafe(env.serviceKey)}`
        );
      }

      if (env.storageUrl) {
        lines.push(
          `NEXT_DB_STORAGE_URL=${envSafe(
            ensureHttp(env.storageUrl)
          )}`
        );
      }
      break;

    // ======================= FIREBASE =======================
    case 'firebase':
      if (env.firebaseConfigJson) {
        lines.push(
          `NEXT_DB_FIREBASE_SERVICE_ACCOUNT=${envSafe(
            serializeServiceAccount(env.firebaseConfigJson)
          )}`
        );
      }

      if (env.firebaseWebConfig) {
        lines.push(
          `NEXT_PUBLIC_FIREBASE_CONFIG=${envSafe(
            serializeFirebaseWebConfig(env.firebaseWebConfig)
          )}`
        );
      }

      if (env.firebaseDbType) {
        lines.push(
          `NEXT_DB_FIREBASE_DB_TYPE=${envSafe(env.firebaseDbType)}`
        );
      }

      if (env.storageUrl) {
        lines.push(
          `NEXT_DB_STORAGE_URL=${envSafe(
            ensureHttp(env.storageUrl)
          )}`
        );
      }
      break;

    default:
      throw new Error(`Unknown DB type: ${env.type}`);
  }

  console.log('🧾 Writing .env.local with lines:\n', lines.join('\n'));

  const startTime = Date.now();

  await writeFile(ENV_FILE_PATH, lines.join('\n') + '\n', 'utf-8');

  console.log('✅ .env.local written in', Date.now() - startTime, 'ms');

  return Date.now() - startTime;
}

// ======================= API =======================
export async function POST(req: Request) {
  try {
    console.log('📩 API POST called');

    const body = await req.json();

    console.log('📥 Body received', body);

    const duration = await writeEnvFileFromObject(body);

    console.log('✅ API completed successfully in', duration, 'ms');

    return new Response(
      JSON.stringify({ success: true, duration }),
      { status: 200 }
    );
  } catch (err: any) {
    console.error('❌ API failed', err);

    return new Response(
      JSON.stringify({ success: false, error: err.message }),
      { status: 500 }
    );
  }
}


// import { writeFile } from 'fs/promises';
// import path from 'path';

// const ENV_FILE_PATH = path.resolve(process.cwd(), '.env.local');
// console.log('📝 ENV write path:', ENV_FILE_PATH);

// function extractMongoDbName(uri: string, fallback?: string) {
//   try {
//     const afterSlash = uri.split('.net/')[1] || '';
//     const dbName = afterSlash.split('?')[0];
//     return dbName || fallback || 'nxt_flutter';
//   } catch {
//     return fallback || 'nxt_flutter';
//   }
// }

// function serializeServiceAccount(value: any) {
//   let obj: any = typeof value === 'string' ? JSON.parse(value) : value;
//   if (obj.private_key) obj.private_key = obj.private_key.replace(/\r?\n/g, '\\n');
//   return JSON.stringify(obj);
// }

// function serializeFirebaseWebConfig(value: string | object) {
//   let obj: any;
//   if (typeof value === 'string') {
//     value = value.trim().replace(/;$/, '');
//     obj = eval('(' + value + ')');
//   } else {
//     obj = value;
//   }
//   return JSON.stringify(obj);
// }

// function ensureHttp(url: string) {
//   if (!url) return url;
//   if (!url.startsWith('http://') && !url.startsWith('https://')) return `https://${url}`;
//   return url;
// }

// async function writeEnvFileFromObject(env: Record<string, any>) {
//   console.log('📦 Received ENV payload:', env);
//   if (!env.type) throw new Error('Missing "type" in env payload');

//   const lines: string[] = [`# Generated by NXT_Flutter Installer`];
//   lines.push(`NEXT_DB_TYPE=${env.type}`);
//   lines.push(`NEXT_PUBLIC_DB_TYPE=${env.type}`);
//   lines.push(`NEXT_PUBLIC_APP_DOMAIN=${ensureHttp(env.domain || 'localhost:3000')}`);

//   switch (env.type) {
//     case 'mongodb':
//       if (!env.connectionString) throw new Error('MongoDB connectionString is required');
//       lines.push(`NEXT_DB_MONGO_URI=${env.connectionString}`);
//       lines.push(`NEXT_DB_MONGO_DB_NAME=${extractMongoDbName(env.connectionString, env.databaseName)}`);
//       break;

//     case 'mysql':
//       if (!env.host || !env.database || !env.user || !env.password)
//         throw new Error('MySQL config missing host, database, user, or password');
//       lines.push(`NEXT_DB_MYSQL_HOST=${env.host}`);
//       lines.push(`NEXT_DB_MYSQL_PORT=${env.port || 3306}`);
//       lines.push(`NEXT_DB_MYSQL_DATABASE=${env.database}`);
//       lines.push(`NEXT_DB_MYSQL_USER=${env.user}`);
//       lines.push(`NEXT_DB_MYSQL_PASSWORD=${env.password}`);
//       break;

//     case 'postgres':
//       if (!env.host || !env.database || !env.user || !env.password)
//         throw new Error('Postgres config missing host, database, user, or password');
//       lines.push(`NEXT_DB_POSTGRES_HOST=${env.host}`);
//       lines.push(`NEXT_DB_POSTGRES_PORT=${env.port || 5432}`);
//       lines.push(`NEXT_DB_POSTGRES_DATABASE=${env.database}`);
//       lines.push(`NEXT_DB_POSTGRES_USER=${env.user}`);
//       lines.push(`NEXT_DB_POSTGRES_PASSWORD=${env.password}`);
//       break;

//     case 'supabase':
//       const supabaseUrl = env.supabaseUrl || env.url;
//       if (!supabaseUrl) throw new Error('Supabase URL missing');
//       lines.push(`NEXT_PUBLIC_SUPABASE_URL=${ensureHttp(supabaseUrl)}`);
//       if (env.anonKey) lines.push(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${env.anonKey}`);
//       if (env.serviceKey) lines.push(`SUPABASE_SERVICE_ROLE_KEY=${env.serviceKey}`);
//       if (env.storageUrl) lines.push(`NEXT_DB_STORAGE_URL=${ensureHttp(env.storageUrl)}`);
//       break;

//     case 'firebase':
//       if (env.firebaseConfigJson) lines.push(`NEXT_DB_FIREBASE_SERVICE_ACCOUNT=${serializeServiceAccount(env.firebaseConfigJson)}`);
//       if (env.firebaseWebConfig) lines.push(`NEXT_PUBLIC_FIREBASE_CONFIG=${serializeFirebaseWebConfig(env.firebaseWebConfig)}`);
//       if (env.firebaseDbType) lines.push(`NEXT_DB_FIREBASE_DB_TYPE=${env.firebaseDbType}`);
//       if (env.storageUrl) lines.push(`NEXT_DB_STORAGE_URL=${ensureHttp(env.storageUrl)}`);
//       break;

//     default:
//       throw new Error(`Unknown DB type: ${env.type}`);
//   }

//   console.log('🧾 Writing .env.local with lines:\n', lines.join('\n'));
//   const startTime = Date.now();
//   await writeFile(ENV_FILE_PATH, lines.join('\n') + '\n', 'utf-8');
//   console.log('✅ .env.local written in', Date.now() - startTime, 'ms');
//   return Date.now() - startTime;
// }

// export async function POST(req: Request) {
//   try {
//     console.log('📩 API POST called');
//     const body = await req.json();
//     console.log('📥 Body received', body);
//     const duration = await writeEnvFileFromObject(body);
//     console.log('✅ API completed successfully in', duration, 'ms');
//     return new Response(JSON.stringify({ success: true, duration }), { status: 200 });
//   } catch (err: any) {
//     console.error('❌ API failed', err);
//     return new Response(JSON.stringify({ success: false, error: err.message }), { status: 500 });
//   }
// }
