import { writeFile } from 'fs/promises';
import path from 'path';

const ENV_FILE_PATH = path.resolve(process.cwd(), '.env.local');
console.log('📝 ENV write path:', ENV_FILE_PATH);

// ======================= SAFE HELPERS =======================

function envSafe(value: any): string {
  if (value === undefined || value === null) return '""';

  if (typeof value === 'number') return String(value);

  const str = String(value);

  return `"${str.replace(/"/g, '\\"')}"`;
}

function ensureHttp(url: string) {
  if (!url) return url;
  if (!url.startsWith('http://') && !url.startsWith('https://')) {
    return `https://${url}`;
  }
  return url;
}

function extractMongoDbName(uri: string, fallback?: string) {
  try {
    const afterSlash = uri.split('.net/')[1] || '';
    const dbName = afterSlash.split('?')[0];
    return dbName || fallback || 'nxt_flutter';
  } catch {
    return fallback || 'nxt_flutter';
  }
}

// ======================= SAFE JSON CORE =======================

function safeJsonParse(input: any) {
  if (!input) return {};

  if (typeof input === 'object') return input;

  if (typeof input !== 'string') return {};

  const cleaned = input
    .trim()
    .replace(/;\s*$/, '')
    .replace(/,\s*}/g, '}')
    .replace(/,\s*]/g, ']');

  return JSON.parse(cleaned);
}

function normalizeServiceAccount(input: any) {
  const obj = safeJsonParse(input);

  if (obj.private_key) {
    obj.private_key = String(obj.private_key)
      .replace(/\\n/g, '\n')
      .replace(/\r\n/g, '\n');
  }

  return obj;
}

// ======================= MAIN WRITER =======================

async function writeEnvFileFromObject(env: Record<string, any>) {
  console.log('📦 Received ENV payload:', env);

  if (!env.type) throw new Error('Missing "type" in env payload');

  const lines: string[] = [`# Generated by NXT_Flutter Installer`];

  // GLOBAL
  lines.push(`NEXT_DB_TYPE=${envSafe(env.type)}`);
  lines.push(`NEXT_PUBLIC_DB_TYPE=${envSafe(env.type)}`);
  lines.push(
    `NEXT_PUBLIC_APP_DOMAIN=${envSafe(
      ensureHttp(env.domain || 'localhost:3000')
    )}`
  );

  // ======================= MONGODB =======================
  if (env.type === 'mongodb') {
    if (!env.connectionString) {
      throw new Error('MongoDB connectionString is required');
    }

    lines.push(`NEXT_DB_MONGO_URI=${envSafe(env.connectionString)}`);
    lines.push(
      `NEXT_DB_MONGO_DB_NAME=${envSafe(
        extractMongoDbName(env.connectionString, env.databaseName)
      )}`
    );
  }

  // ======================= MYSQL =======================
  if (env.type === 'mysql') {
    if (!env.host || !env.database || !env.user || !env.password) {
      throw new Error('MySQL config missing required fields');
    }

    lines.push(`NEXT_DB_MYSQL_HOST=${envSafe(env.host)}`);
    lines.push(`NEXT_DB_MYSQL_PORT=${envSafe(env.port || 3306)}`);
    lines.push(`NEXT_DB_MYSQL_DATABASE=${envSafe(env.database)}`);
    lines.push(`NEXT_DB_MYSQL_USER=${envSafe(env.user)}`);
    lines.push(`NEXT_DB_MYSQL_PASSWORD=${envSafe(env.password)}`);
  }

  // ======================= POSTGRES =======================
  if (env.type === 'postgres') {
    if (!env.host || !env.database || !env.user || !env.password) {
      throw new Error('Postgres config missing required fields');
    }

    lines.push(`NEXT_DB_POSTGRES_HOST=${envSafe(env.host)}`);
    lines.push(`NEXT_DB_POSTGRES_PORT=${envSafe(env.port || 5432)}`);
    lines.push(`NEXT_DB_POSTGRES_DATABASE=${envSafe(env.database)}`);
    lines.push(`NEXT_DB_POSTGRES_USER=${envSafe(env.user)}`);
    lines.push(`NEXT_DB_POSTGRES_PASSWORD=${envSafe(env.password)}`);
  }

  // ======================= SUPABASE =======================
  if (env.type === 'supabase') {
    const url = env.supabaseUrl || env.url;
    if (!url) throw new Error('Supabase URL missing');

    lines.push(
      `NEXT_PUBLIC_SUPABASE_URL=${envSafe(ensureHttp(url))}`
    );

    if (env.anonKey) {
      lines.push(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${envSafe(env.anonKey)}`);
    }

    if (env.serviceKey) {
      lines.push(`SUPABASE_SERVICE_ROLE_KEY=${envSafe(env.serviceKey)}`);
    }

    if (env.storageUrl) {
      lines.push(
        `NEXT_DB_STORAGE_URL=${envSafe(ensureHttp(env.storageUrl))}`
      );
    }
  }

  // ======================= FIREBASE (FIXED) =======================
  if (env.type === 'firebase') {
    const serviceAccount = normalizeServiceAccount(env.firebaseConfigJson);
    const webConfig = safeJsonParse(env.firebaseWebConfig);

    lines.push(
      `NEXT_DB_FIREBASE_SERVICE_ACCOUNT=${envSafe(
        JSON.stringify(serviceAccount)
      )}`
    );

    lines.push(
      `NEXT_PUBLIC_FIREBASE_CONFIG=${envSafe(
        JSON.stringify(webConfig)
      )}`
    );

    if (env.firebaseDbType) {
      lines.push(
        `NEXT_DB_FIREBASE_DB_TYPE=${envSafe(env.firebaseDbType)}`
      );
    }

    if (env.storageUrl) {
      lines.push(
        `NEXT_DB_STORAGE_URL=${envSafe(ensureHttp(env.storageUrl))}`
      );
    }
  }

  console.log('🧾 FINAL ENV OUTPUT:\n', lines.join('\n'));

  await writeFile(ENV_FILE_PATH, lines.join('\n') + '\n', 'utf-8');

  console.log('✅ .env.local successfully written');
}

// ======================= API =======================

export async function POST(req: Request) {
  try {
    const body = await req.json();

    const duration = await writeEnvFileFromObject(body);

    return new Response(
      JSON.stringify({ success: true, duration }),
      { status: 200 }
    );
  } catch (err: any) {
    console.error('❌ API FAILED:', err);

    return new Response(
      JSON.stringify({
        success: false,
        error: err.message,
      }),
      { status: 500 }
    );
  }
}