/**
 * ApiPage.tsx
 * ------------
 * The API management page of the Underpeaks console.
 * Located at: /console/api
 *
 * What does this page do?
 * ------------------------
 * It gives developers a full view of the API layer that Underpeaks automatically
 * generates from your CMS models, plus tools to manage API keys and test endpoints.
 *
 * The page is split into three tabs:
 *
 *  1. Endpoints tab
 *     Shows all auto-generated REST endpoints (created automatically from your models)
 *     and any custom endpoints you have added. Includes search and filter controls,
 *     and each endpoint row can be expanded to see example requests and run a test.
 *
 *  2. API Keys tab
 *     Lists all API keys for the project. Keys can be revealed, copied, or deleted.
 *     New keys can be generated by entering a name and clicking Generate.
 *
 *  3. Reference tab
 *     Static documentation showing all supported query parameters, filter operators,
 *     and a full worked example of a complex API query.
 *
 * What are "auto" vs "custom" endpoints?
 * ----------------------------------------
 * - Auto endpoints are generated automatically by Underpeaks for every model you create.
 *   For example, if you have a "Products" model, Underpeaks generates GET, POST, PUT,
 *   and DELETE endpoints for it automatically — no code required.
 * - Custom endpoints are written by you (or your developers) to contain business logic
 *   that goes beyond simple CRUD — for example, creating an order, sending a confirmation
 *   email, and decrementing stock all in one API call.
 *
 * ⚠️  Security notes:
 *   - API key generation MUST be moved to the server before production (see createKey TODO)
 *   - Full API key values are held in component state — they should only be fetched
 *     from the server when the user explicitly reveals them, not stored in the UI
 */

'use client'

import { useState } from 'react'
import { useTranslations } from 'next-intl'
import {
  FiCode, FiCopy, FiCheck, FiPlay, FiPlus, FiTrash2,
  FiChevronDown, FiChevronUp, FiKey, FiLock, FiUnlock,
  FiEdit2, FiX, FiZap, FiEye, FiEyeOff,
} from 'react-icons/fi'

// ─────────────────────────────────────────────────────────────────
// TYPE DEFINITIONS
// ─────────────────────────────────────────────────────────────────

/**
 * HttpMethod
 * -----------
 * The set of HTTP methods supported by the API builder.
 * These map directly to REST conventions:
 *  - GET    → read/list data
 *  - POST   → create new data
 *  - PUT    → replace existing data
 *  - DELETE → remove data
 *  - PATCH  → partially update data
 */
type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'

/**
 * EndpointType
 * -------------
 * Whether an endpoint was auto-generated by Underpeaks from a model ('auto')
 * or manually created by a developer with custom business logic ('custom').
 */
type EndpointType = 'auto' | 'custom'

/**
 * Endpoint
 * ---------
 * Represents a single API endpoint shown in the Endpoints tab.
 *
 * @prop id          - Unique identifier for the endpoint
 * @prop method      - HTTP method (GET, POST, etc.)
 * @prop path        - The URL path (e.g. '/api/data/products/:id')
 * @prop description - A human-readable description of what the endpoint does
 * @prop type        - Whether this is auto-generated or a custom endpoint
 * @prop model       - The CMS model this endpoint belongs to (auto endpoints only)
 * @prop auth        - Whether this endpoint requires an API key / Bearer token
 */
type Endpoint = {
  id:          string
  method:      HttpMethod
  path:        string
  description: string
  type:        EndpointType
  model?:      string
  auth:        boolean
}

/**
 * ApiKey
 * -------
 * Represents a single API key entry shown in the API Keys tab.
 *
 * @prop id       - Unique identifier for the key
 * @prop name     - A human-readable label for the key (e.g. 'Production Key')
 * @prop key      - The actual API key string. In production this should only
 *                  be fetched from the server when the user explicitly reveals it.
 * @prop created  - Human-readable creation date string
 * @prop lastUsed - Human-readable last-used date string, or 'Never'
 * @prop active   - Whether the key is currently active and usable
 */
type ApiKey = {
  id:       string
  name:     string
  key:      string
  created:  string
  lastUsed: string
  active:   boolean
}

// ─────────────────────────────────────────────────────────────────
// MOCK DATA
// ─────────────────────────────────────────────────────────────────

/**
 * TODO: Replace mockEndpoints with a real API call to fetch endpoints from the database.
 * The endpoint list should be loaded from the server based on the project's models
 * and any custom endpoints the user has created.
 * Suggested API: GET /api/endpoints/list
 */
const mockEndpoints: Endpoint[] = [
  { id: '1',  method: 'GET',    path: '/api/data/products',       description: 'List all products with filtering and pagination', type: 'auto',   model: 'Products', auth: false },
  { id: '2',  method: 'GET',    path: '/api/data/products/:id',   description: 'Get a single product by ID',                     type: 'auto',   model: 'Products', auth: false },
  { id: '3',  method: 'POST',   path: '/api/data/products',       description: 'Create a new product',                          type: 'auto',   model: 'Products', auth: true  },
  { id: '4',  method: 'PUT',    path: '/api/data/products/:id',   description: 'Update a product by ID',                        type: 'auto',   model: 'Products', auth: true  },
  { id: '5',  method: 'DELETE', path: '/api/data/products/:id',   description: 'Delete a product by ID',                        type: 'auto',   model: 'Products', auth: true  },
  { id: '6',  method: 'GET',    path: '/api/data/orders',         description: 'List all orders with filtering and pagination',  type: 'auto',   model: 'Orders',   auth: true  },
  { id: '7',  method: 'GET',    path: '/api/data/orders/:id',     description: 'Get a single order by ID',                      type: 'auto',   model: 'Orders',   auth: true  },
  { id: '8',  method: 'POST',   path: '/api/data/orders',         description: 'Create a new order',                            type: 'auto',   model: 'Orders',   auth: true  },
  { id: '9',  method: 'PUT',    path: '/api/data/orders/:id',     description: 'Update an order by ID',                         type: 'auto',   model: 'Orders',   auth: true  },
  { id: '10', method: 'GET',    path: '/api/data/users',          description: 'List all users',                                type: 'auto',   model: 'Users',    auth: true  },
  { id: '11', method: 'GET',    path: '/api/data/users/:id',      description: 'Get a single user by ID',                       type: 'auto',   model: 'Users',    auth: true  },
  { id: '12', method: 'POST',   path: '/api/custom/checkout',     description: 'Create order, send email, decrement stock',     type: 'custom', auth: true  },
  { id: '13', method: 'GET',    path: '/api/custom/sales-report', description: 'Aggregated sales report across models',         type: 'custom', auth: true  },
  { id: '14', method: 'POST',   path: '/api/custom/webhook',      description: 'Inbound webhook receiver',                      type: 'custom', auth: false },
]

/**
 * TODO: Replace mockApiKeys with a real API call.
 * Keys should be loaded from the server. Full key values should NOT be returned
 * by the list endpoint — only the masked version. The full key should only be
 * retrievable immediately after creation (shown once) or via an explicit
 * "reveal" server call that logs the access for audit purposes.
 */
const mockApiKeys: ApiKey[] = [
  { id: '1', name: 'Production Key', key: 'nxt_live_4f8a2b9c3d1e7f6a5b4c3d2e1f0a9b8c', created: '10 Jan 2025', lastUsed: '25 Apr 2025', active: true  },
  { id: '2', name: 'Dev Key',        key: 'nxt_test_1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d', created: '15 Jan 2025', lastUsed: '24 Apr 2025', active: true  },
  { id: '3', name: 'CI/CD Key',      key: 'nxt_test_9z8y7x6w5v4u3t2s1r0q9p8o7n6m5l4', created: '1 Mar 2025',  lastUsed: 'Never',       active: false },
]

// ─────────────────────────────────────────────────────────────────
// REFERENCE DATA (static — no TODO needed, this is documentation)
// ─────────────────────────────────────────────────────────────────

/**
 * queryParams
 * ------------
 * The list of query parameters supported by all auto-generated GET endpoints.
 * Displayed in the Reference tab as a parameter reference table.
 */
const queryParams = [
  { param: 'limit',   type: 'number', description: 'Max results to return (default: 20)'      },
  { param: 'offset',  type: 'number', description: 'Number of results to skip for pagination'  },
  { param: 'where',   type: 'string', description: 'Filter: field:operator:value (repeatable)' },
  { param: 'orderBy', type: 'string', description: 'Sort: field:asc or field:desc'             },
  { param: 'select',  type: 'string', description: 'Comma-separated fields to return'          },
]

/**
 * operators
 * ----------
 * The filter operators supported in the `where` query parameter.
 * Each entry has the operator name and a usage example.
 * Displayed in the Reference tab as an operator reference table.
 */
const operators = [
  { op: 'eq',   example: 'status:eq:active'     },
  { op: 'neq',  example: 'status:neq:draft'      },
  { op: 'gt',   example: 'price:gt:100'          },
  { op: 'gte',  example: 'price:gte:100'         },
  { op: 'lt',   example: 'price:lt:500'          },
  { op: 'lte',  example: 'price:lte:500'         },
  { op: 'like', example: 'name:like:shoe'        },
  { op: 'in',   example: 'status:in:active,paid' },
]

// ─────────────────────────────────────────────────────────────────
// STYLE CONSTANTS
// ─────────────────────────────────────────────────────────────────

/**
 * methodColors
 * -------------
 * Maps each HTTP method to a set of Tailwind CSS classes for the method badge.
 * Each method has a distinct colour so they can be identified at a glance.
 */
const methodColors: Record<HttpMethod, string> = {
  GET:    'bg-green-50 text-green-700 border-green-200',
  POST:   'bg-blue-50 text-blue-700 border-blue-200',
  PUT:    'bg-amber-50 text-amber-700 border-amber-200',
  DELETE: 'bg-red-50 text-red-700 border-red-200',
  PATCH:  'bg-purple-50 text-purple-700 border-purple-200',
}

// ─────────────────────────────────────────────────────────────────
// SUB-COMPONENTS
// ─────────────────────────────────────────────────────────────────

/**
 * MethodBadge
 * ------------
 * A small coloured pill that displays an HTTP method (GET, POST, etc.).
 * The colour is determined by the methodColors map above.
 *
 * @param method - The HTTP method to display
 */
function MethodBadge({ method }: { method: HttpMethod }) {
  return (
    <span
      className={`inline-block px-2 py-0.5 text-[10px] font-bold rounded border w-14 text-center shrink-0 ${methodColors[method]}`}
      aria-label={method}
    >
      {method}
    </span>
  )
}

/**
 * CopyButton
 * -----------
 * A small icon button that copies a given text string to the clipboard.
 * Shows a green checkmark for 2 seconds after copying to confirm the action.
 *
 * @param text - The string to copy to the clipboard when clicked
 */
function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  const t = useTranslations('apiPage')

  return (
    <button
      onClick={() => {
        navigator.clipboard.writeText(text)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
      }}
      className="p-1 rounded hover:bg-gray-100 text-gray-400 hover:text-gray-700 transition shrink-0"
      aria-label={copied ? t('copied') : t('copy')}
      title={copied ? t('copied') : t('copy')}
    >
      {copied
        ? <FiCheck size={13} className="text-green-500" aria-hidden="true" />
        : <FiCopy size={13} aria-hidden="true" />
      }
    </button>
  )
}

/**
 * EndpointRow
 * ------------
 * Renders a single endpoint as a collapsible row in the endpoints list.
 *
 * Collapsed state (default):
 *  Shows the method badge, path, description, model badge, auth icon,
 *  a copy button for the example URL, and a "Test" button on hover.
 *
 * Expanded state (when clicked):
 *  Shows an example request URL in a dark code block, the required
 *  Authorization header (if auth is required), and optionally a test panel
 *  where the user can send a mock request and see a mock response.
 *
 * @param endpoint - The endpoint data to display
 */
function EndpointRow({ endpoint }: { endpoint: Endpoint }) {
  // Controls whether the detail panel is shown below the row
  const [expanded, setExpanded] = useState(false)

  // Controls whether the test panel is shown within the expanded detail panel
  const [testOpen, setTestOpen] = useState(false)

  // The mock response JSON string shown in the test panel after running a test
  const [response, setResponse] = useState('')

  // Whether a test request is currently "in flight" (shows loading state on button)
  const [loading, setLoading] = useState(false)

  const t = useTranslations('apiPage')

  // Build the example URL shown in the expanded panel
  // GET endpoints include common query params as a usage hint
  const exampleUrl = `https://yourapp.com${endpoint.path}${
    endpoint.method === 'GET' ? '?limit=20&offset=0' : ''
  }`

  /**
   * runTest
   * --------
   * Simulates sending a request to this endpoint and shows a mock response.
   *
   * TODO: Replace this mock implementation with a real API call to the endpoint.
   * In production, this should actually call the endpoint (with the user's API key)
   * and display the real response — not a hardcoded mock.
   * The 800ms timeout simulates network latency for now.
   */
  const runTest = () => {
    setLoading(true)
    setTimeout(() => {
      setResponse(JSON.stringify({
        data: endpoint.method === 'GET'
          ? [{ id: '1', name: 'Example Item', status: 'active', created_at: new Date().toISOString() }]
          : { success: true, id: Date.now().toString() },
        total:   endpoint.method === 'GET' ? 1     : undefined,
        limit:   endpoint.method === 'GET' ? 20    : undefined,
        offset:  endpoint.method === 'GET' ? 0     : undefined,
        hasMore: endpoint.method === 'GET' ? false : undefined,
      }, null, 2))
      setLoading(false)
    }, 800)
  }

  return (
    <div className="border-b border-gray-100 last:border-0">

      {/* ── Collapsed row — always visible ── */}
      <div
        className="flex items-center gap-3 px-5 py-3 hover:bg-gray-50 cursor-pointer transition-colors group"
        onClick={() => setExpanded((v) => !v)}
        role="button"
        aria-expanded={expanded}
        tabIndex={0}
        onKeyDown={(e) => e.key === 'Enter' && setExpanded((v) => !v)}
      >
        <MethodBadge method={endpoint.method} />
        <p className="text-sm font-mono text-gray-800 flex-1 truncate">{endpoint.path}</p>
        <p className="text-xs text-gray-400 hidden md:block flex-1 truncate">{endpoint.description}</p>

        <div className="flex items-center gap-2 shrink-0">
          {/* Model badge — shows which CMS model this endpoint belongs to */}
          {endpoint.model && (
            <span className="text-[10px] bg-blue-50 text-blue-600 border border-blue-100 px-2 py-0.5 rounded-full font-medium hidden sm:block">
              {endpoint.model}
            </span>
          )}

          {/* Custom endpoint badge */}
          {endpoint.type === 'custom' && (
            <span className="text-[10px] bg-violet-50 text-violet-600 border border-violet-100 px-2 py-0.5 rounded-full font-medium hidden sm:block">
              {t('endpoints.customBadge')}
            </span>
          )}

          {/* Auth indicator — lock icon if auth required, unlock if public */}
          {endpoint.auth
            ? <FiLock size={12} className="text-amber-500" title={t('endpoints.requiresAuth')} aria-label={t('endpoints.requiresAuth')} />
            : <FiUnlock size={12} className="text-gray-300" title={t('endpoints.public')} aria-label={t('endpoints.public')} />
          }

          <CopyButton text={exampleUrl} />

          {/* Test button — only visible on row hover */}
          <button
            onClick={(e) => { e.stopPropagation(); setTestOpen((v) => !v) }}
            className="flex items-center gap-1 px-2 py-1 text-[10px] font-medium bg-gray-100 hover:bg-gray-800 hover:text-white text-gray-600 rounded transition opacity-0 group-hover:opacity-100"
            aria-label={t('endpoints.testButton')}
          >
            <FiPlay size={10} aria-hidden="true" />
            {t('endpoints.testButton')}
          </button>

          {/* Expand/collapse chevron */}
          {expanded
            ? <FiChevronUp size={14} className="text-gray-400" aria-hidden="true" />
            : <FiChevronDown size={14} className="text-gray-400" aria-hidden="true" />
          }
        </div>
      </div>

      {/* ── Expanded panel — shown when row is clicked ── */}
      {expanded && (
        <div className="px-5 pb-4 bg-gray-50 border-t border-gray-100">
          <div className="mt-3 flex flex-col gap-3">

            {/* Example request URL in a dark code block */}
            <div>
              <p className="text-[10px] font-semibold text-gray-400 uppercase mb-1">
                {t('endpoints.exampleRequest')}
              </p>
              <div className="flex items-center gap-2 px-3 py-2 bg-gray-900 rounded-md">
                <span className={`text-[10px] font-bold ${
                  endpoint.method === 'GET'    ? 'text-green-400' :
                  endpoint.method === 'POST'   ? 'text-blue-400'  :
                  endpoint.method === 'DELETE' ? 'text-red-400'   : 'text-amber-400'
                }`}>
                  {endpoint.method}
                </span>
                <p className="text-xs text-gray-300 font-mono flex-1 truncate">{exampleUrl}</p>
                <CopyButton text={exampleUrl} />
              </div>
            </div>

            {/* Required auth header — only shown if this endpoint requires auth */}
            {endpoint.auth && (
              <div>
                <p className="text-[10px] font-semibold text-gray-400 uppercase mb-1">
                  {t('endpoints.requiredHeaders')}
                </p>
                <div className="px-3 py-2 bg-gray-900 rounded-md">
                  <p className="text-xs font-mono text-gray-300">
                    Authorization: Bearer <span className="text-amber-400">{'<your-api-key>'}</span>
                  </p>
                </div>
              </div>
            )}

            {/* Test panel — shown when the Test button is clicked */}
            {testOpen && (
              <div>
                <p className="text-[10px] font-semibold text-gray-400 uppercase mb-1">
                  {t('endpoints.testLabel')}
                </p>
                <div className="flex flex-col gap-2">
                  <button
                    onClick={runTest}
                    disabled={loading}
                    className="flex items-center gap-1.5 px-3 py-2 bg-gray-900 text-white text-xs font-medium rounded-md hover:bg-gray-700 disabled:opacity-50 transition w-fit"
                  >
                    <FiPlay size={11} aria-hidden="true" />
                    {loading ? t('endpoints.running') : t('endpoints.sendRequest')}
                  </button>

                  {/* Mock response output */}
                  {response && (
                    <pre className="text-[11px] bg-gray-900 text-green-400 font-mono p-3 rounded-md overflow-x-auto">
                      {response}
                    </pre>
                  )}
                </div>
              </div>
            )}

          </div>
        </div>
      )}
    </div>
  )
}

/**
 * CustomEndpointDrawer
 * ----------------------
 * A slide-in panel from the right side of the screen for creating a new custom endpoint.
 *
 * What is a custom endpoint?
 * ---------------------------
 * Unlike auto-generated endpoints (which Underpeaks creates from your models),
 * custom endpoints contain your own business logic. For example, you might create
 * a POST /api/custom/checkout endpoint that creates an order, sends a confirmation
 * email, and decrements stock — all in one API call.
 *
 * The drawer lets you configure:
 *  - HTTP method (GET, POST, PUT, DELETE, PATCH)
 *  - URL path (must start with /api/custom/)
 *  - Description
 *  - Authentication requirement (required or public)
 *  - Handler code (a JavaScript function template to fill in)
 *
 * @param open     - Whether the drawer is currently visible
 * @param onClose  - Callback to close the drawer (called by cancel button and backdrop click)
 * @param onCreate - Callback called with the new Endpoint object when the user clicks Create
 */
function CustomEndpointDrawer({ open, onClose, onCreate }: {
  open:     boolean
  onClose:  () => void
  onCreate: (e: Endpoint) => void
}) {
  const [method,      setMethod]      = useState<HttpMethod>('POST')
  const [path,        setPath]        = useState('/api/custom/')
  const [description, setDescription] = useState('')
  const [auth,        setAuth]        = useState(true)
  const [code,        setCode]        = useState(
`// Custom endpoint handler
// Call your generic API, add business logic, integrate services

export async function handler(req, res) {
  const { productId, quantity } = req.body;
  const product = await fetch(\`/api/data/products/\${productId}\`);
  // Your business logic here
  return res.json({ success: true });
}`
  )

  const t = useTranslations('apiPage')

  // Don't render anything if the drawer is closed — avoids keeping it in the DOM
  if (!open) return null

  return (
    <>
      {/* Semi-transparent backdrop — clicking it closes the drawer */}
      <div
        className="fixed inset-0 bg-black/20 z-40"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Drawer panel */}
      <div
        className="fixed top-16 right-0 bottom-0 w-full max-w-lg bg-white border-l border-gray-200 z-50 flex flex-col shadow-2xl"
        role="dialog"
        aria-modal="true"
        aria-label={t('drawer.title')}
      >

        {/* Drawer header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100 shrink-0">
          <div>
            <h2 className="text-sm font-bold text-gray-900">{t('drawer.title')}</h2>
            <p className="text-xs text-gray-400 mt-0.5">{t('drawer.subtitle')}</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600"
            aria-label={t('drawer.close')}
          >
            <FiX size={18} aria-hidden="true" />
          </button>
        </div>

        {/* Drawer form content */}
        <div className="flex-1 overflow-y-auto px-5 py-4 flex flex-col gap-4">

          {/* Method + Path row */}
          <div className="flex gap-2">
            <div className="flex flex-col gap-1">
              <label className="text-xs font-semibold text-gray-700">{t('drawer.methodLabel')}</label>
              <select
                value={method}
                onChange={(e) => setMethod(e.target.value as HttpMethod)}
                className="px-3 py-2 text-sm border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-300 transition"
                aria-label={t('drawer.methodLabel')}
              >
                {(['GET', 'POST', 'PUT', 'DELETE', 'PATCH'] as HttpMethod[]).map((m) => (
                  <option key={m}>{m}</option>
                ))}
              </select>
            </div>
            <div className="flex flex-col gap-1 flex-1">
              <label className="text-xs font-semibold text-gray-700">{t('drawer.pathLabel')}</label>
              <input
                value={path}
                onChange={(e) => setPath(e.target.value)}
                placeholder="/api/custom/my-endpoint"
                className="px-3 py-2 text-sm border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-300 focus:bg-white transition font-mono"
                aria-label={t('drawer.pathLabel')}
              />
            </div>
          </div>

          {/* Description field */}
          <div className="flex flex-col gap-1">
            <label className="text-xs font-semibold text-gray-700">{t('drawer.descriptionLabel')}</label>
            <input
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder={t('drawer.descriptionPlaceholder')}
              className="px-3 py-2 text-sm border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-300 focus:bg-white transition"
              aria-label={t('drawer.descriptionLabel')}
            />
          </div>

          {/* Authentication toggle */}
          <div className="flex flex-col gap-1">
            <label className="text-xs font-semibold text-gray-700">{t('drawer.authLabel')}</label>
            <div className="flex gap-2" role="group" aria-label={t('drawer.authLabel')}>
              <button
                onClick={() => setAuth(true)}
                className={`flex-1 flex items-center justify-center gap-1.5 py-2 text-xs font-medium rounded-md border transition ${
                  auth ? 'bg-gray-900 text-white border-gray-900' : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'
                }`}
                aria-pressed={auth}
              >
                <FiLock size={12} aria-hidden="true" />
                {t('drawer.authRequired')}
              </button>
              <button
                onClick={() => setAuth(false)}
                className={`flex-1 flex items-center justify-center gap-1.5 py-2 text-xs font-medium rounded-md border transition ${
                  !auth ? 'bg-gray-900 text-white border-gray-900' : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'
                }`}
                aria-pressed={!auth}
              >
                <FiUnlock size={12} aria-hidden="true" />
                {t('drawer.authPublic')}
              </button>
            </div>
          </div>

          {/* Handler code editor */}
          <div className="flex flex-col gap-1 flex-1">
            <label className="text-xs font-semibold text-gray-700">{t('drawer.codeLabel')}</label>
            <textarea
              value={code}
              onChange={(e) => setCode(e.target.value)}
              rows={16}
              className="w-full px-3 py-2 text-xs font-mono border border-gray-200 rounded-md bg-gray-900 text-green-400 focus:outline-none focus:ring-2 focus:ring-gray-500 transition resize-none"
              aria-label={t('drawer.codeLabel')}
              spellCheck={false}
            />
          </div>

        </div>

        {/* Drawer footer actions */}
        <div className="shrink-0 px-5 py-4 border-t border-gray-100 flex gap-2">
          <button
            onClick={onClose}
            className="flex-1 py-2.5 bg-white border border-gray-200 text-gray-700 text-sm font-medium rounded-md hover:bg-gray-50 transition"
          >
            {t('drawer.cancelButton')}
          </button>
          <button
            onClick={() => {
              onCreate({
                id:          Date.now().toString(),
                method,
                path,
                description,
                type:        'custom',
                auth,
              })
              onClose()
            }}
            disabled={!path.trim()}
            className="flex-1 py-2.5 bg-gray-900 text-white text-sm font-medium rounded-md hover:bg-gray-700 disabled:opacity-40 transition"
          >
            {t('drawer.createButton')}
          </button>
        </div>

      </div>
    </>
  )
}

/**
 * ApiKeysSection
 * ---------------
 * The content rendered in the "API Keys" tab.
 * Shows a list of all API keys with reveal/copy/delete actions,
 * and a form to generate a new key.
 *
 * What is an API key?
 * --------------------
 * An API key is a secret token that client applications (your Flutter or Next.js app)
 * must include in their requests to access protected API endpoints.
 * It is sent as a Bearer token in the Authorization header:
 *   Authorization: Bearer nxt_live_xxxx...
 *
 * Key masking:
 * -------------
 * By default, keys are shown in a masked format (first 12 chars + dots + last 4 chars).
 * The user can click the eye icon to reveal the full key. This is a UI-only protection —
 * the full key is already in memory. In production, full keys should only be fetched
 * from the server on explicit reveal, not returned in the initial list load.
 */
function ApiKeysSection() {
  const [keys,       setKeys]       = useState<ApiKey[]>(mockApiKeys)
  const [newName,    setNewName]    = useState('')
  const [revealed,   setRevealed]   = useState<Set<string>>(new Set())
  const [deletingId, setDeletingId] = useState<string | null>(null)

  const t = useTranslations('apiPage')

  /**
   * toggleReveal
   * -------------
   * Shows or hides the full API key value for a given key ID.
   * Uses a Set to track which keys are currently revealed.
   *
   * @param id - The API key ID to toggle
   */
  const toggleReveal = (id: string) => {
    setRevealed((prev) => {
      const next = new Set(prev)
      next.has(id) ? next.delete(id) : next.add(id)
      return next
    })
  }

  /**
   * maskKey
   * --------
   * Returns a masked version of an API key for safe display.
   * Shows the prefix (first 12 characters), then dots, then the last 4 characters.
   * Example: 'nxt_live_4f8a' + '••••••••••••••••••••' + '9b8c'
   *
   * @param key - The full API key string
   * @returns     The masked version for display
   */
  const maskKey = (key: string) => key.slice(0, 12) + '••••••••••••••••••••' + key.slice(-4)

  /**
   * createKey
   * ----------
   * Generates a new API key with the name entered by the user and adds it to the list.
   *
   * ⚠️  SECURITY WARNING — MUST FIX BEFORE PRODUCTION:
   * This currently generates the key client-side using Math.random(), which is NOT
   * cryptographically secure. API keys generated this way are predictable and unsafe.
   *
   * Before going to production:
   *  1. Move key generation to a server action or API route
   *  2. Use Node's crypto.randomBytes() on the server (as in forgotPassword.ts)
   *  3. Store only a hash of the key in the database (never the plain key)
   *  4. Return the full key to the client ONCE immediately after creation
   *     and make clear it cannot be shown again — just like GitHub personal access tokens
   *
   * Suggested API: POST /api/api-keys/create → returns { key: 'nxt_live_...' }
   */
  const createKey = () => {
    if (!newName.trim()) return

    // TODO: Replace this entire block with a server API call
    const chars = 'abcdef0123456789'
    const rand  = Array.from(
      { length: 32 },
      () => chars[Math.floor(Math.random() * chars.length)]
    ).join('')

    setKeys((prev) => [...prev, {
      id:       Date.now().toString(),
      name:     newName.trim(),
      key:      `nxt_live_${rand}`,
      created:  new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }),
      lastUsed: t('keys.never'),
      active:   true,
    }])
    setNewName('')
  }

  return (
    <div className="flex flex-col gap-4">

      {/* ── Existing API Keys List ── */}
      <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
        <div className="px-5 py-3 border-b border-gray-100 bg-gray-50 flex items-center justify-between">
          <p className="text-xs font-bold text-gray-700">{t('keys.title')}</p>
          <p className="text-[10px] text-gray-400">{t('keys.keepSecret')}</p>
        </div>

        {keys.map((k) => (
          <div
            key={k.id}
            className="flex items-center gap-3 px-5 py-3 border-b border-gray-100 last:border-0 group"
          >
            <div className="flex-1 min-w-0">
              {/* Key name and active/inactive badge */}
              <div className="flex items-center gap-2">
                <p className="text-sm font-semibold text-gray-800">{k.name}</p>
                <span className={`text-[10px] px-1.5 py-0.5 rounded-full font-medium ${
                  k.active ? 'bg-green-50 text-green-600' : 'bg-gray-100 text-gray-400'
                }`}>
                  {k.active ? t('keys.active') : t('keys.inactive')}
                </span>
              </div>

              {/* Masked or revealed key value with reveal toggle and copy button */}
              <div className="flex items-center gap-2 mt-0.5">
                <p className="text-xs font-mono text-gray-400">
                  {revealed.has(k.id) ? k.key : maskKey(k.key)}
                </p>
                <button
                  onClick={() => toggleReveal(k.id)}
                  className="text-gray-400 hover:text-gray-600"
                  aria-label={revealed.has(k.id) ? t('keys.hideKey') : t('keys.revealKey')}
                >
                  {revealed.has(k.id)
                    ? <FiEyeOff size={11} aria-hidden="true" />
                    : <FiEye size={11} aria-hidden="true" />
                  }
                </button>
                <CopyButton text={k.key} />
              </div>

              {/* Created and last used dates */}
              <p className="text-[10px] text-gray-400 mt-0.5">
                {t('keys.created')} {k.created} · {t('keys.lastUsed')} {k.lastUsed}
              </p>
            </div>

            {/* Delete confirmation — shown on hover, requires a confirm click */}
            <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
              {deletingId === k.id ? (
                // Confirm / cancel delete buttons
                <>
                  <button
                    onClick={() => {
                      setKeys((prev) => prev.filter((key) => key.id !== k.id))
                      setDeletingId(null)
                    }}
                    className="flex items-center justify-center w-7 h-7 rounded bg-red-50 text-red-500 hover:bg-red-100 transition"
                    aria-label={t('keys.confirmDelete')}
                  >
                    <FiCheck size={13} aria-hidden="true" />
                  </button>
                  <button
                    onClick={() => setDeletingId(null)}
                    className="flex items-center justify-center w-7 h-7 rounded bg-gray-100 text-gray-500 hover:bg-gray-200 transition"
                    aria-label={t('keys.cancelDelete')}
                  >
                    <FiX size={13} aria-hidden="true" />
                  </button>
                </>
              ) : (
                // Initial delete button — clicking moves to confirm state
                <button
                  onClick={() => setDeletingId(k.id)}
                  className="flex items-center justify-center w-7 h-7 rounded bg-gray-100 text-gray-500 hover:bg-red-50 hover:text-red-500 transition"
                  aria-label={t('keys.deleteKey', { name: k.name })}
                >
                  <FiTrash2 size={13} aria-hidden="true" />
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* ── Create New Key ── */}
      <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
        <div className="px-5 py-3 border-b border-gray-100 bg-gray-50">
          <p className="text-xs font-bold text-gray-700">{t('keys.createTitle')}</p>
        </div>
        <div className="px-5 py-4 flex gap-2">
          <input
            value={newName}
            onChange={(e) => setNewName(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && createKey()}
            placeholder={t('keys.namePlaceholder')}
            className="flex-1 px-3 py-2 text-sm border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-300 focus:bg-white transition"
            aria-label={t('keys.nameLabel')}
          />
          <button
            onClick={createKey}
            disabled={!newName.trim()}
            className="flex items-center gap-1.5 px-4 py-2 bg-gray-900 text-white text-sm font-medium rounded-md hover:bg-gray-700 disabled:opacity-40 transition"
          >
            <FiKey size={13} aria-hidden="true" />
            {t('keys.generateButton')}
          </button>
        </div>
      </div>

    </div>
  )
}

// ─────────────────────────────────────────────────────────────────
// MAIN PAGE COMPONENT
// ─────────────────────────────────────────────────────────────────

/**
 * ApiPage
 * --------
 * The root component for the /console/api page.
 * Manages top-level tab state, endpoint filtering, search, and the drawer.
 */
export default function ApiPage() {
  const [activeTab,   setActiveTab]   = useState<'endpoints' | 'keys' | 'reference'>('endpoints')
  const [filterModel, setFilterModel] = useState<string>('all')
  const [filterType,  setFilterType]  = useState<'all' | 'auto' | 'custom'>('all')
  const [endpoints,   setEndpoints]   = useState<Endpoint[]>(mockEndpoints)
  const [drawerOpen,  setDrawerOpen]  = useState(false)
  const [search,      setSearch]      = useState('')

  const t = useTranslations('apiPage')

  // Build the list of model filter options from the endpoints data.
  // 'all' is always first, followed by unique model names extracted from auto endpoints.
  const models = ['all', ...Array.from(
    new Set(mockEndpoints.filter((e) => e.model).map((e) => e.model!))
  )]

  // Apply all three active filters (model, type, search) to the full endpoint list
  const filtered = endpoints.filter((e) => {
    const matchModel  = filterModel === 'all' || e.model === filterModel
    const matchType   = filterType  === 'all' || e.type  === filterType
    const matchSearch = (
      e.path.toLowerCase().includes(search.toLowerCase()) ||
      e.description.toLowerCase().includes(search.toLowerCase())
    )
    return matchModel && matchType && matchSearch
  })

  // Tab configuration — id must match the activeTab union type
  const tabs = [
    { id: 'endpoints', label: t('tabs.endpoints'), count: endpoints.length              },
    { id: 'keys',      label: t('tabs.keys'),      count: mockApiKeys.filter((k) => k.active).length },
    { id: 'reference', label: t('tabs.reference'), count: null                          },
  ] as const

  return (
    <div className="absolute inset-0 flex flex-col bg-gray-100 overflow-hidden">

      {/* ── Toolbar ── */}
      <div className="shrink-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
        <div>
          <h1 className="text-base font-bold text-gray-900">{t('title')}</h1>
          <p className="text-xs text-gray-400 mt-0.5">{t('subtitle')}</p>
        </div>
        <button
          onClick={() => setDrawerOpen(true)}
          className="flex items-center gap-1.5 px-4 py-2 bg-gray-900 text-white text-sm font-medium rounded-md hover:bg-gray-700 transition"
          aria-label={t('customEndpointButton')}
        >
          <FiPlus size={15} aria-hidden="true" />
          {t('customEndpointButton')}
        </button>
      </div>

      {/* ── Tabs ── */}
      <div
        className="shrink-0 bg-white border-b border-gray-200 px-6 flex gap-0"
        role="tablist"
        aria-label={t('tabsLabel')}
      >
        {tabs.map((tab) => (
          <button
            key={tab.id}
            role="tab"
            aria-selected={activeTab === tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-1.5 px-4 py-3 text-sm font-medium border-b-2 transition-colors ${
              activeTab === tab.id
                ? 'border-gray-900 text-gray-900'
                : 'border-transparent text-gray-500 hover:text-gray-700'
            }`}
          >
            {tab.label}
            {tab.count !== null && (
              <span className="text-[10px] bg-gray-100 text-gray-500 px-1.5 py-0.5 rounded-full font-medium">
                {tab.count}
              </span>
            )}
          </button>
        ))}
      </div>

      {/* ── Tab Content ── */}
      <div className="flex-1 overflow-y-auto p-6">

        {/* ── Endpoints Tab ── */}
        {activeTab === 'endpoints' && (
          <div className="flex flex-col gap-4 max-w-5xl mx-auto">

            {/* Filter bar: search + type filter + model filter */}
            <div className="flex items-center gap-3 flex-wrap">
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder={t('endpoints.searchPlaceholder')}
                className="px-3 py-2 text-sm border border-gray-200 rounded-md bg-white focus:outline-none focus:ring-2 focus:ring-gray-300 transition w-56"
                aria-label={t('endpoints.searchPlaceholder')}
              />

              {/* Type filter: all / auto / custom */}
              <div
                className="flex items-center border border-gray-200 rounded-md overflow-hidden bg-white text-xs font-medium"
                role="group"
                aria-label={t('endpoints.typeFilterLabel')}
              >
                {(['all', 'auto', 'custom'] as const).map((type) => (
                  <button
                    key={type}
                    onClick={() => setFilterType(type)}
                    aria-pressed={filterType === type}
                    className={`px-3 py-2 capitalize border-r border-gray-200 last:border-0 transition-colors ${
                      filterType === type ? 'bg-gray-100 text-gray-900' : 'text-gray-500 hover:bg-gray-50'
                    }`}
                  >
                    {t(`endpoints.type.${type}`)}
                  </button>
                ))}
              </div>

              {/* Model filter: all + each unique model name */}
              <div
                className="flex items-center border border-gray-200 rounded-md overflow-hidden bg-white text-xs font-medium"
                role="group"
                aria-label={t('endpoints.modelFilterLabel')}
              >
                {models.map((m) => (
                  <button
                    key={m}
                    onClick={() => setFilterModel(m)}
                    aria-pressed={filterModel === m}
                    className={`px-3 py-2 capitalize border-r border-gray-200 last:border-0 transition-colors ${
                      filterModel === m ? 'bg-gray-100 text-gray-900' : 'text-gray-500 hover:bg-gray-50'
                    }`}
                  >
                    {m}
                  </button>
                ))}
              </div>
            </div>

            {/* Endpoints table */}
            <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
              {/* Table header */}
              <div className="grid grid-cols-[80px_1fr_1fr_auto] gap-x-4 px-5 py-2.5 border-b border-gray-100 bg-gray-50">
                <p className="text-[10px] font-bold text-gray-400 uppercase">{t('endpoints.colMethod')}</p>
                <p className="text-[10px] font-bold text-gray-400 uppercase">{t('endpoints.colPath')}</p>
                <p className="text-[10px] font-bold text-gray-400 uppercase">{t('endpoints.colDescription')}</p>
                <p className="text-[10px] font-bold text-gray-400 uppercase">{t('endpoints.colActions')}</p>
              </div>

              {/* Endpoint rows */}
              {filtered.map((e) => <EndpointRow key={e.id} endpoint={e} />)}

              {/* Empty state */}
              {filtered.length === 0 && (
                <div className="flex items-center justify-center py-12 text-gray-400">
                  <p className="text-sm">{t('endpoints.noResults')}</p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* ── API Keys Tab ── */}
        {activeTab === 'keys' && (
          <div className="max-w-2xl mx-auto">
            <ApiKeysSection />
          </div>
        )}

        {/* ── Reference Tab ── */}
        {activeTab === 'reference' && (
          <div className="max-w-3xl mx-auto flex flex-col gap-6">

            {/* Query Parameters table */}
            <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
              <div className="px-5 py-3.5 border-b border-gray-100 bg-gray-50">
                <p className="text-sm font-bold text-gray-800">{t('reference.queryParamsTitle')}</p>
                <p className="text-xs text-gray-400 mt-0.5">{t('reference.queryParamsSubtitle')}</p>
              </div>
              <div className="divide-y divide-gray-100">
                {queryParams.map((p) => (
                  <div key={p.param} className="flex items-start gap-4 px-5 py-3">
                    <code className="text-xs font-mono bg-gray-100 px-2 py-0.5 rounded text-gray-800 shrink-0">
                      {p.param}
                    </code>
                    <span className="text-[10px] text-blue-600 bg-blue-50 px-1.5 py-0.5 rounded shrink-0">
                      {p.type}
                    </span>
                    <p className="text-xs text-gray-600">{p.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Filter Operators table */}
            <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
              <div className="px-5 py-3.5 border-b border-gray-100 bg-gray-50">
                <p className="text-sm font-bold text-gray-800">{t('reference.operatorsTitle')}</p>
                <p className="text-xs text-gray-400 mt-0.5">
                  {t('reference.operatorsSubtitle')}{' '}
                  <code className="bg-gray-100 px-1 rounded">where</code>{' '}
                  {t('reference.operatorsFormat')}{' '}
                  <code className="bg-gray-100 px-1 rounded">field:operator:value</code>
                </p>
              </div>
              <div className="grid grid-cols-2 divide-y divide-gray-100">
                {operators.map((o) => (
                  <div
                    key={o.op}
                    className="flex items-center gap-3 px-5 py-3 border-r border-gray-100 odd:border-r even:border-r-0"
                  >
                    <code className="text-xs font-mono bg-gray-100 px-2 py-0.5 rounded text-gray-800 w-10 text-center shrink-0">
                      {o.op}
                    </code>
                    <code className="text-xs font-mono text-gray-500">{o.example}</code>
                  </div>
                ))}
              </div>
            </div>

            {/* Full worked example */}
            <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
              <div className="px-5 py-3.5 border-b border-gray-100 bg-gray-50">
                <p className="text-sm font-bold text-gray-800">{t('reference.exampleTitle')}</p>
              </div>
              <div className="px-5 py-4 flex flex-col gap-3">
                <p className="text-xs text-gray-500">{t('reference.exampleDescription')}</p>
                <div className="flex items-start gap-2 px-3 py-3 bg-gray-900 rounded-md">
                  <pre className="text-xs text-green-400 font-mono whitespace-pre-wrap flex-1">{`GET /api/data/products
  ?where=status:eq:active
  &where=price:lt:500
  &orderBy=price:asc
  &select=id,name,price
  &limit=20
  &offset=0`}</pre>
                  <CopyButton text="/api/data/products?where=status:eq:active&where=price:lt:500&orderBy=price:asc&select=id,name,price&limit=20&offset=0" />
                </div>
                <p className="text-xs text-gray-500 mt-1">{t('reference.responseLabel')}</p>
                <pre className="text-xs bg-gray-900 text-green-400 font-mono p-3 rounded-md overflow-x-auto">{`{
  "data": [
    { "id": "1", "name": "Running Shoes", "price": 299 },
    { "id": "2", "name": "Yoga Mat",      "price": 149 }
  ],
  "total":   2,
  "limit":   20,
  "offset":  0,
  "hasMore": false
}`}</pre>
              </div>
            </div>

          </div>
        )}

      </div>

      {/* Custom endpoint creation drawer */}
      <CustomEndpointDrawer
        open={drawerOpen}
        onClose={() => setDrawerOpen(false)}
        onCreate={(e) => setEndpoints((prev) => [...prev, e])}
      />

    </div>
  )
}